// Palimpsest — version history, newest first. The code is the commit the
// version was built from; the current build's own code comes from the build
// stamp (window.__PALIMPSEST_BUILD) and is shown with the top entry.
export const VERSIONS = [
  { v: '1.13.0', date: '2026-09-24', notes: 'The North, and the women the fur trade ran on. A new chapter from Belshaw’s eighth: the Thule crossing the Arctic from Alaska to Labrador, why the Inuit had little use for the fur trade, the village of 1,000 at the mouth of the Mackenzie, Franklin’s four failures, the Cree monopolies that ran the trade the Hudson’s Bay Company waited on, the women whose work it depended on — “the emergent Plains culture owed almost as much to women as it did to horses and guns” — and the making of the Métis, Michif and the pemmican trade. The Inuit had appeared nowhere in the app; nine questions in the whole pack had a woman as their subject. Also: questions that tested the same thing as another are down from 60 clusters to 6, the fill-the-gap questions now take a different sentence from the one their chapter already quotes, and the build refuses two questions sharing an id — which had quietly made one card of two questions.' },
  { v: '1.12.0', date: '2026-09-24', notes: 'Not always four options, and a timeline that grows with you. Three new things to be asked: who said this (a quoted voice, four speakers), oldest first (three dated events from different regions), and fill the gap (a sentence you have seen as evidence, with a name or place taken out). They are spread through the order new questions arrive in, alternating, so no two days set the same task — about one in nine of a fortnight’s questions now, where it was one in thirty. The line of centres on the opening screen is no longer fixed: once you have met a few dated questions it shows your own — the earliest year you have met, the latest, and two between, spaced so their labels never collide, with a caption that says so. 531 questions.' },
  { v: '1.11.0', date: '2026-09-23', notes: 'Lighter, and two new sources. The books no longer travel inside the app: the page is 1.3 MB instead of 8.6, and both volumes are fetched only when you open the library or a passage — the difference between opening this on a phone and waiting for it. New: “Exchange and obligation”, twenty-one questions from OpenStax’s Introduction to Anthropology on how goods moved before markets — the potlatch, hxaro gift partnerships, Hawaiian tribute, what money is for, and the claim this app was built on but had never asked: that swapping goods on the spot “was never a dominant form of exchange in any culture in the past”. And Haiti in its own words, from the state papers Prince Saunders published in London in 1816: a general of the revolution demanding to see the law that guarantees freedom, the French commander admitting it does not exist yet, and a decree dated “in the seventh year of the independence of Hayti”. 471 questions. About now lists every source the questions actually cite, with its licence, built from the pack rather than written by hand.' },
  { v: '1.10.0', date: '2026-09-23', notes: 'The world, written out. The Caribbean and the Atlantic, China and East Asia, South Asia and the Indian Ocean, the Islamic world and Europe all have written questions now — 123 of them, so 288 written and 417 in all. Europe is one region among the others rather than the line the others are measured against. Three audits behind it: accuracy (every date, name, quantity and wrong option checked against the passage it cites), question quality, and design. From those: the answer options now follow your reading size instead of staying at 16.5px; the sentence that proves the answer gets the full width of the card instead of 21 characters a line; quiet mode no longer leaves an empty strip down the screen where the read-aloud buttons were; Home puts the two things you came to do above the lists to browse; back from a thread or a round-end returns to it rather than Home; Progress, About, the thread and the round-end can be read aloud; and every question says whose history it asks about — a thread question now says “China and Asia · 1557”. The glossary questions no longer draw their wrong answers from each other, which is what made them feel like the same four sentences over and over; half of them now ask for the word rather than the meaning.' },
  { v: '1.9.0', date: '2026-09-23', notes: 'Fewer repeats, more history. No question comes back the next day any more: the shortest gap is two days, a question you get right first time waits three, and one you keep missing backs off instead of arriving every morning. New questions keep their share of every round even when reviews are waiting. In a simulated fortnight of two rounds a day this took what you see from 66 questions to 110, with no next-day repeats at all — and a 90-day study of two learners showed more of the app met and more of it known. New: “I’m in public”, one switch on Home and in Settings that turns off sound and takes the read-aloud buttons away.' },
  { v: '1.8.1', date: '2026-09-20', notes: 'Every question says whose history it is asking about: the chapter or region above the question, with the year where the question has one. The Amazonia questions now name the Bolivian Amazon themselves.' },
  { v: '1.8.0', date: '2026-09-19', code: '9d6ea8b', notes: 'Around the world: six regions — Africa, the Caribbean and the Atlantic, China and East Asia, South Asia and the Indian Ocean, the Islamic world, Europe — from OpenStax World History (both volumes). Africa has 23 written questions; every region has its big questions and questions generated from the textbooks’ own glossaries (152 across the app, including Belshaw’s), checked like the rest. 317 questions in all.' },
  { v: '1.7.1', date: '2026-09-19', code: '3b40da6', notes: 'Fix: Home and the chapters promised new questions after the day’s allowance was used, and opened an empty round (“Nothing to ask here yet”). They now show what a round will hold, and offer a recall test or “Learn more anyway”.' },
  { v: '1.7.0', date: '2026-09-19', code: 'c71333f', notes: 'The first thread across the world: Trade, empire and abolition, 1488–1842 — Macau, the East India Company, the Canton system and the Opium Wars, the Napoleonic Wars and 1812, and the end of slavery in Canada and the British Empire, with what is known of life under it in the British Caribbean. A timeline in four regions, 24 questions, and “Meanwhile” on the answer card. New sources: OpenStax World History, Mary Prince (1831), Anders Ljungstedt on Macau (1836).' },
  { v: '1.6.0', date: '2026-09-19', code: '0010e07', notes: 'The recall test (was Practice): the questions you’re likeliest to have forgotten come first. A question answered in the last four hours waits, even if you close and reopen the app, unless there’s nothing else to ask. Similar questions are kept apart: no more than two on one big question in a round, never side by side, never two from the same passage.' },
  { v: '1.5.0', date: '2026-09-19', code: 'ea14275', notes: '“Where do you start?”: eight questions, easy to hard, that set your pace and give you a starting point to measure against. A shorter answer card: the key sentence and one line naming the big question; the rest on tap.' },
  { v: '1.4.0', date: '2026-09-19', code: '3102f86', notes: 'Showing growth: what you can answer, with a line of it rising and this week’s change; “then and now” for questions you missed at first and later got right; a map of how much of each big question you can answer; the round-end card says what changed.' },
  { v: '1.3.0', date: '2026-09-18', code: '584f6ae', notes: 'No question repeats within a session. Every round brings new questions, and the count shown is exact. The first rounds start from familiar history, with a fact taught in each question. Version history with dates and codes.' },
  { v: '1.2.2', date: '2026-09-18', code: 'ea64c91', notes: 'Questions never name their source; the build now refuses any that do. One more question reworded.' },
  { v: '1.2.1', date: '2026-09-18', code: 'b3bb83f', notes: 'Seventeen questions rewritten to stand on their own, with context in the question.' },
  { v: '1.2.0', date: '2026-09-18', code: '33fcdd2', notes: 'The bigger picture: big questions for each chapter, sixteen new questions on causes and consequences, details asked after.' },
  { v: '1.1.0', date: '2026-09-18', code: '45c95e6', notes: 'Today’s voice on Home; all the voices; About with sources and licences; installable from the web.' },
  { v: '1.0.0', date: '2026-09-18', code: '919558b', notes: 'Four chapters, the library, read-aloud, sound, and the Amazonia chapter.' },
];
